<?php

/**
 * @file
 * Provides development tools for sites using Solr.
 */

/**
 * Implements hook_permission().
 */
function devel_node_access_permission() {
  return array(
    'view solr_devel information' => array(
      'description' => t('View the devel information for Solr searches. Raw data is returned by Solr meaning that sensitive data could be exposed that would normally be protected by various access control systems.'),
      'title' => t('Access Solr Devel Information'),
      'restrict access' => TRUE,
    ),
  );
}

/**
 * Implements hook_menu().
 */
function solr_devel_menu() {
  $items = array();

  $items['node/%node/devel/solr'] = array(
    'title' => 'Solr Index',
    'page callback' => 'solr_devel_node_overview_page',
    'page arguments' => array(1),
    'access arguments' => array('view solr_devel information'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'solr_devel.pages.inc',
  );

  $items['node/%node/devel/solr/%solr_devel_environment/queue'] = array(
    'title' => 'Solr Queue Analysis',
    'page callback' => 'solr_devel_node_queue_analysis_page',
    'page arguments' => array(1, 4),
    'access arguments' => array('view solr_devel information'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'solr_devel.pages.inc',
  );

  return $items;
}

/**
 * Implements hook_solr_devel_environment_info().
 */
function apachesolr_solr_devel_environment_info() {
  $info = array();
  foreach (apachesolr_load_all_environments() as $env_id => $environment) {
    $info['apachesolr:' . $env_id] = array(
      'label' => 'Apache Solr: ' . $environment['name'],
      'adapter' => 'Drupal_SolrDevel_Adapter_ApacheSolr',
      'adapter options' => array('env_id' => $env_id),
    );
  }
  return $info;
}

/**
 * Gets environment info.
 *
 * @return array
 *   An array of environment info.
 */
function solr_devel_get_environment_info() {
  $environments = array();
  foreach (module_invoke_all('solr_devel_environment_info') as $name => $info) {
    $environments[$name] = $info + array(
      'name' => $name,
      'label' => $name,
      'adapter options' => array(),
    );
  }
  return $environments;
}

/**
 * Loads an environment.
 *
 * @param string $id
 *   The unique identifier of the environment.
 *
 * @return array|FALSE
 *   The environment definition, FALE if not available.
 */
function solr_devel_environment_load($id) {
  $environments = solr_devel_get_environment_info();
  return isset($environments[$id]) ? $environments[$id] : FALSE;
}

/**
 * Loads an adapter from an environment definition.
 *
 * @return Drupal_SolrDevel_Adapter
 *   The adapter instance.
 */
function solr_devel_adapter_load(array $environment) {
  return new $environment['adapter']($environment['label'], $environment['adapter options']);
}
